### ISSUE TITLE
Program failed to run

### ISSUE THREAD

**Issue by classheadmaster** [HydroLAB-UNIBAS/GFA-Geomorphic-Flood-Area#1]
I copied the plug-in QGIS installation directory and run it with banchmark data，but window tips that：

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices 
Traceback (most recent call last):
  File "C:/Users/Administrator.USER-20170228KZ/.qgis2/python/plugins\GeomorphicFloodIndex\doGeomorphicFloodIndex.py 

", line 711, in accept
    Ariver[ctr,ctc]=flowacc[X[x,y],Y[x,y]]# use X[x,y],Y[x,y]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by HydroLAB-UNIBAS** [comment]
The plug-in is run on QGIS version with python 2.7. Moreover, Input files are:
DEM is 'dem_srtem_subbasin30m.txt'
Filled DEm is 'demfilled_srtm_subbasin30m.yxy'
Flow Direction D8 is 'flowdir_subbasin30m.txt'
Flow accumulation is 'flowacc_subbasin30m.txt'
If you want to  Calibrate Threshold you need to use as Standard flood hazard map the file 'floodhazardmap_subbasin30m.txt'

**Comment by HydroLAB-UNIBAS** [comment]
New numpy version accepts int: line 711 and 712 was modified.
